---
title: "Resources"
description: |
  Categorized Links to Helpful Resources
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Programming Resources
* [An Introduction to R](https://cran.r-project.org/doc/manuals/R-intro.pdf): Downloadable PDF for new R users
* [Quick-R](https://www.statmethods.net/): Useful resource for beginners
* [CRAN Task Views](https://cran.r-project.org/web/views/): R packages by topic
* [Advanced R](http://adv-r.had.co.nz/): Hadley Wickham's Guide to Advanced R Programming
* [DataCamp](https://www.datacamp.com/): Interactive courses & tutorials for learning R programming
* [Customizing RStudio](https://support.rstudio.com/hc/en-us/articles/200549016-Customizing-RStudio#general): RStudio Software Preference Guide
* [RStudio Connections](https://support.rstudio.com/hc/en-us/articles/115010915687): Guide to connecting RStudio to data sources

## R Markdown
* [Kieran Healy](https://kieranhealy.org/resources/): General resources for R Markdown ouput from Duke's Dr. Kieran Healy 
* [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/): Detailed guide from the original package writers
* [R Markdown: Reference Guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf): Downloadable PDF of guide to basic markdown syntax
* [R Markdown: Gallery of Outputs](https://rmarkdown.rstudio.com/gallery.html): Examples of possible R markdown ouput
* [R Markdown Chunk Options](https://yihui.name/knitr/options/#chunk-options): Guide for R code chunk evaluation options
* [List of LaTeX Mathematical Symbols](https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols): LaTeX symbol syntax
* [Exhaustive List of Mathematical Symbols with Meanings](https://sciencestruck.com/list-of-mathematical-symbols-their-meaning): List of mathematical symbols (in case you don't remember a symbol's name)
* [Prettydoc HTML Templates](https://cran.r-project.org/web/packages/prettydoc/vignettes/architect.html): A few R markdown HTML templates
* [Tufte Handout Template](https://rstudio.github.io/tufte/): Another nice template
