---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: resume.tex
geometry: margin=.5in

title: "Resume"
author: Patrick Raymond Oster

fontawesome: yes  
email: poster@luc.edu  
github: patrickoster
twitter: your_twitter
phone: "+1 (618) 975-3915"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
urlcolor: blue
---

# Education

**Accelerated Graduate Program: M.Sc. in Applied Statistics** \hfill Graduation: May 2019  
**B.Sc. in Statistics & B.A. in Economics** \hfill 2014 - 2018  
*Department of Mathematics & Statistics, Loyola University Chicago* \hfill GPA: 3.5  

- Awards/Honors: Interdisciplinary Honors Program, Dean's List, International Leadership Certificate Recipient, National Society of Collegiate Scholars
- Graduate Coursework: Multivariate Analysis, Categorical Data Analysis, Nonparametric Statistical Methods, Regression Analysis, Sampling Methods, Statistical Consulting
- Undergraduate Coursework: Predictive Analytics, Design of Experiments, Computational Modeling & Simulation, Econometrics, Labor Market Analysis, Urban Economics, International Monetary Policy

# Professional Experience

**Service Delivery & Operations Intern** \hfill June 2018 - Aug 2018  
*Health Care Service Corporation* \hfill Chicago, IL

- Created a reporting dashboard for executive level communications regarding progress on a large scale technology project; refined data cleaning, structuring & visualization skills using excel, R, & Tableau
- Developed healthcare industry knowledge, technical skills, professional network, & business acumen through a structured internship program at BlueCross BlueShield headquarters in Chicago

**Digital Media Advisor/Graduate Assistant** \hfill Sept 2015 - present  
*Digital Media Services - LUC* \hfill Chicago, IL

- Improve leadership & collaborative abilities by supporting & training Digital Media Advisors in assisting students, faculty, & alumni with software packages, production equipment, & various multimedia tools & applications
- Develop problem-solving & process-improvement focus by managing online academic poster printing queue, troubleshooting & repairing damaged equipment, & completing digital media projects
- Improve problem-solving skills by providing excellent customer service while using scheduling/inventory software

# Leadership & Service

**Labre Homeless Outreach Program** \hfill Chicago, IL  
*Student Companion Leader* \hfill April 2017 - May 2018  

- Volunteered to lead students in standing in solidarity with downtown Chicago’s homeless population by providing food & drink on a weekly basis in order to be men & women for & with others
- Prepared group reflections for before & after each session to promote love & learning among the community

**Sigma Chi Fraternity - Lambda Nu Chapter** \hfill Chicago, IL  
*Brother At Large/Webmaster* \hfill Dec 2016 - Dec 2017  

- Executive board member responsible for gauging & representing the general opinion of the chapter on executive votes
- Updated & managed the Sigma Chi Lambda Nu chapter website (http://www.sigmachiluc.com/)

**Lodge of Ondessonk Service & Honor Society** \hfill Ozark, IL  
*President* \hfill July 2015 - Aug 2016  

- Coordinated service opportunities for thousands of active adult & youth members
- Organized & conducted biannual meetings regarding changes to the constitution & the elections of regional officials
- Co-presenter at the 2016 Midstates ACA conference on effective camper/volunteer retention strategies

# Skills, Activities & Interests

- Technical Skills: RStudio, SAS, Tableau, SQL, Minitab, Stata, JIRA, LaTeX, Markdown
- Activities: Summer camp volunteer, Math/Stat/Econ tutor, Club Lacrosse
- Interests: Machine Learning/AI, Healthcare, Pharmaceuticals, Technology, Behavioral Economics
